name: HexVG-DatabaseAddon
version: 1.2.0
main: com.venomgrave.hexvg.database.HexVGAddon
api-version: 1.16
authors: [VenomGrave]
description: Skript database addon for VenomGrave servers

softdepend:
  - Skript
  - PlaceholderAPI

commands:
  hexvgdb:
    description: HexVG DatabaseAddon management command
    usage: /hexvgdb <debug|status|reload>
    permission: hexvg.database.admin

permissions:
  hexvg.database.admin:
    description: Access to HexVG-DatabaseAddon management commands
    default: op
